[versions]
agp = "8.13.0"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"

pagingTesting = "3.3.6"
retrofit2 = "2.11.0"
coreSplashscreen = "1.0.1"
hiltAndroid = "2.52"
gson = "2.11.0"
room = "2.6.1"
navigation = "2.8.5"
hilt-navigation-compose = "1.2.0"
googleService = "4.4.2"
ksp = "2.0.21-1.0.27"
paging-compose = "3.3.6"
okHttp = "4.12.0"
landscapist = "2.3.6"
junitJupiter = "5.8.1"
turbine = "1.0.0"
coroutine-test = "1.8.1"
hilt-test = "2.51"
mockk = "1.13.12"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-paging-testing = { module = "androidx.paging:paging-testing", version.ref = "pagingTesting" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
com-retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }
com-google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
androidx-room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-test = { group = "com.google.dagger", name= "hilt-android-testing", version.ref = "hilt-test" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging-compose" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
landscapist-coil = { module = "com.github.skydoves:landscapist-coil", version.ref = "landscapist" }
landscapist-placeholder = { module = "com.github.skydoves:landscapist-placeholder", version.ref = "landscapist" }
landscapist-animation = { module = "com.github.skydoves:landscapist-animation", version.ref = "landscapist" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
androidx-cash-turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
androidx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine-test" }
mockk-io = { module = "io.mockk:mockk", version.ref = "mockk" }
#landscapist-bom = { module = "com.github.skydoves:landscapist-bom", version.ref = "landscapist" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleService" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }